language: ruby

rvm:
  - 2.2.3

env:
  - DB=sqlite
  - DB=postgresql

script:
  - ENV=test RAILS_ENV=test bundle exec rails db:drop db:create db:migrate
  - ENV=test RAILS_ENV=test bundle exec rails db:migrate:status
  - bundle exec rspec spec

before_script:
  - rm -rf db/*.sqlite3
  - psql -c 'create database codingyard_test' -U postgres

notifications:
  email: false
