language: ruby

env:
  - DB=sqlite
  - DB=postgresql

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - bundle exec rspec spec

before_script:
  - psql -c 'create database codingyard_test' -U postgres

notifications:
  email: false
